[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-Z", "codegen-backend=cranelift",
  "-Z", "threads=8",
  "-C", "link-arg=-fuse-ld=/home/apika/.dotfiles/bin/mold"
]
