- defaults:
    link:
      create: true
      relink: true

- link:
    "~/.gitconfig":
    "~/fishrc.fish":
    "~/Monocraft.otf":
    "~/.cargo/config.toml":
      path: "cargo/config.toml"
    "~/.config/bottom":
      path: "config/bottom"
    "~/.config/fish":
      path: "config/fish"
    "~/.config/neofetch":
      path: "config/neofetch"
    "~/.config/nvim":
      path: "config/nvim"
    "~/.config/starship.toml": 
      path: "config/starship.toml"

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  # - git update-submodules
